# Site settings
title: currenjin's wiki
url: "https://currenjin.github.io"
baseurl: ""
description: >
    행복합시다, 우리!

# My information
email: hyun0524e@naver.com
author: currenjin
profile: 정현진
github_username: currenjin
instagram_username: currenjin
comment-support: utterances

# Build settings
plugins:
  - jekyll-gist

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: currenjin
  shortname: currenjin
utterances:
  repo: currenjin/currenjin.github.io
  issue-term: url
  label: Comment
  branch: main

google_analytics:
  ua: #FIXME

google_adsense:
  client: #FIXME

blame: "https://github.com/currenjin/currenjin.github.io/blame/main/_wiki"
edit: "https://github.com/currenjin/currenjin.github.io/edit/main/_wiki"
issue: "https://github.com/currenjin/currenjin.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
